### PR TITLE
(chore): Using PowerShell Core instead of PowerShell Desktop

### PR DESCRIPTION
**Pull request by Baneeishaque**

### CODE REVIEW

**Comment by Baneeishaque** [comment]
**Is there any specific reason to stick to PowerShell Desktop instead of PowerShell Core?**

Will anything break if we switch from PowerShell Desktop to PowerShell Core? If something breaks and we can fix it on the Scoop side, we can work on it. But, if it needs to be fixed on the PowerShell Core side - we can try to work on it.

_Most of my manifests leverage on checkver.script field and these scripts are developed under PowerShell Core. So, these are not compatible with PowerShell Desktop. That's why, I want to switch from PowerShell Desktop to PowerShell Core in my Excavator GitHub Actions._

If we want to stick on PowerShell Desktop for some reason, I have to migrate the scripts to PowerShell Desktop compatibility. Since PowerShell Core is the future, I think that migration is a waste of resources. Anyway, If migration is necessary - I am ready for it.

**Comment by HUMORCE** [comment]
- Windows PowerShell is a pre-installed system component that stopped updating with new features but still in lifecycle.
- PowerShell Core is not a replacement for Windows PowerShell. 

Scoop should work [out of the box](https://github.com/ScoopInstaller/Install?tab=readme-ov-file#prerequisites). Even the Scoop Core project itself makes limited use of the new features available in PowerShell Core.

**Review by rasa — APPROVED** [review]
If it introduces issues, we can always revert it back.

**Comment by niheaven** [comment]
It's GitHub Actions, using PowerShell should be ok, IMO.

**Comment by chawyehsu** [comment]
Hi, sorry for late repsonse on this, but this has to be reverted as it is intentional to use `powershell` to run actions. The `ConvertFrom-Json` function from `pwsh` can be problematic because it can not detect tailing commas when validating JSON files.

There had been issues of invalid JSON manfiests being committed to official buckets, led to checks for Scoop [being taken down on repology](https://github.com/repology/repology-updater/commit/48f3d4cfddee2dbe0bd74f086e9dc8b67e780300). We don't want this to happen again and that's why `powershell` was used (`ConvertFrom-Json` from `powershell` throws error on detecting tailing commas).

For 3rd party buckets, if you don't care about PowerShell 5 compatiblity, which is still officially supported by Scoop, you're always free to fork this actions repo and switch to the fork with the running shell changed to `pwsh` for your own buckets.

Tip: if you are not sure why one line of code is written like that or want to know the commit histroy of that line of code, you may use git blame to do such investigation, which may provide you context you might not know, before taking further action. It is also available on the GitHub web interface.
image

**Comment by niheaven** [comment]
Reverts by https://github.com/ScoopInstaller/GithubActions/commit/944bf8edad33a51180b9bc006044fab88dc245c8 and requires further investigation

**Comment by o-l-a-v** [comment]
PowerShell v7.5.0 supports detecting trailing commas with `Test-Json` for instance:

* <https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/test-json?view=powershell-7.5#-options>

image

So if `$PSversionTable.PSVersion -ge '7.4'` to a `Test-Json` too?

**Pull request merged**
